// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjTMVr2c5LM2Gm6JdQ8hj07V9FrnUSb6k',
    appId: '1:128279594465:web:48d7a1e092e8cc25b17ea0',
    messagingSenderId: '128279594465',
    projectId: 'training2023-e8aa2',
    authDomain: 'training2023-e8aa2.firebaseapp.com',
    storageBucket: 'training2023-e8aa2.appspot.com',
    measurementId: 'G-GRB8DSTK5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCkyVXlqSRrSdgj-oYtmLQSf_U4Pq7jHo',
    appId: '1:128279594465:android:d42cdf0a53d5d003b17ea0',
    messagingSenderId: '128279594465',
    projectId: 'training2023-e8aa2',
    storageBucket: 'training2023-e8aa2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVFU_4oCMwBcmHHKfOi-UMhrGB6Ow5bUo',
    appId: '1:128279594465:ios:ca35dbdc8b6fec47b17ea0',
    messagingSenderId: '128279594465',
    projectId: 'training2023-e8aa2',
    storageBucket: 'training2023-e8aa2.appspot.com',
    iosBundleId: 'com.example.flutterMfaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVFU_4oCMwBcmHHKfOi-UMhrGB6Ow5bUo',
    appId: '1:128279594465:ios:ca35dbdc8b6fec47b17ea0',
    messagingSenderId: '128279594465',
    projectId: 'training2023-e8aa2',
    storageBucket: 'training2023-e8aa2.appspot.com',
    iosBundleId: 'com.example.flutterMfaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjTMVr2c5LM2Gm6JdQ8hj07V9FrnUSb6k',
    appId: '1:128279594465:web:13f248480bb6f4d3b17ea0',
    messagingSenderId: '128279594465',
    projectId: 'training2023-e8aa2',
    authDomain: 'training2023-e8aa2.firebaseapp.com',
    storageBucket: 'training2023-e8aa2.appspot.com',
    measurementId: 'G-0RE277MSWP',
  );
}
